#!/usr/bin/env python

import getopt
import sys
import os
import subprocess
import re

args = sys.argv[1:]
if len(sys.argv) < 2:
    sys.stderr.write('Usage: %s <commit_range> <changeid>...' % sys.argv[0])
    sys.exit(1)

range = sys.argv[1]
changeids = sys.argv[2:]

re_commit = re.compile(r'commit ([0-9a-f]{40}) \1')
re_changeid = re.compile(r'ChangeID: ([0-9a-f]{40})')

cmd = 'git log --pretty=format:commit\ %H\ %H%n%b ' + range
p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
found = {}
for line in p.stdout:
    m = re_commit.match(line)
    if m:
	commit = m.group(1)
	if commit in changeids:
	    found[commit] = commit
	changeid = None
	continue

    if not changeid:
	m = re_changeid.match(line)
	if m:
	    changeid = m.group(1)
	    if changeid in changeids:
		found[changeid] = commit

for changeid in changeids:
    if changeid in found:
	commitid = found[changeid]
	sys.stdout.write('%s\n' % commitid)
	sys.stdout.flush()
    else:
    	sys.stderr.write('Changeid %s not found\n' % changeid)

